name: alpha
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  loader_overlay: ^4.0.1
  firebase_core: ^3.3.0
  shared_preferences: ^2.3.2
  animated_introduction: ^1.0.4
  firebase_auth: ^5.1.4
  flutter_riverpod: ^2.5.1
  get: ^4.6.6
  loading_animation_widget: ^1.2.1
  extended_phone_number_input: ^1.0.2
  logger: ^2.4.0
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  image_stack: ^2.1.1
  cloud_firestore: ^5.2.1
  sidebarx: ^0.17.1
  cached_network_image: ^3.4.0
  skeletonizer: ^1.4.2
  file_picker: ^8.0.7
  intl: ^0.19.0
  firebase_storage: ^12.2.0
  path: ^1.9.0
  image_picker: ^1.1.2
  csc_picker: ^0.2.7
  open_filex: ^4.5.0
  dio: ^5.7.0
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  syncfusion_flutter_pdfviewer: ^26.2.13
  json_annotation: ^4.9.0
  tap_to_expand: ^0.7.2
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
