// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFPLdUInrChLXRN9YCF8_lXudvotE17O0',
    appId: '1:1042293949658:web:3e27d3e6b3561a214891e3',
    messagingSenderId: '1042293949658',
    projectId: 'miningassociation-8942c',
    authDomain: 'miningassociation-8942c.firebaseapp.com',
    databaseURL: 'https://miningassociation-8942c.firebaseio.com',
    storageBucket: 'miningassociation-8942c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8vXCDE2Rsgdd0Yl_jvUsf_qSPhA4n_Hc',
    appId: '1:1042293949658:android:083b242b7cb654104891e3',
    messagingSenderId: '1042293949658',
    projectId: 'miningassociation-8942c',
    databaseURL: 'https://miningassociation-8942c.firebaseio.com',
    storageBucket: 'miningassociation-8942c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIJjQip2QXFLf6evVZiVnlxp-wMlllwFM',
    appId: '1:1042293949658:ios:b6aff5c2feb80a014891e3',
    messagingSenderId: '1042293949658',
    projectId: 'miningassociation-8942c',
    databaseURL: 'https://miningassociation-8942c.firebaseio.com',
    storageBucket: 'miningassociation-8942c.appspot.com',
    iosBundleId: 'com.example.alpha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIJjQip2QXFLf6evVZiVnlxp-wMlllwFM',
    appId: '1:1042293949658:ios:b6aff5c2feb80a014891e3',
    messagingSenderId: '1042293949658',
    projectId: 'miningassociation-8942c',
    databaseURL: 'https://miningassociation-8942c.firebaseio.com',
    storageBucket: 'miningassociation-8942c.appspot.com',
    iosBundleId: 'com.example.alpha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFPLdUInrChLXRN9YCF8_lXudvotE17O0',
    appId: '1:1042293949658:web:908af15fea9bac514891e3',
    messagingSenderId: '1042293949658',
    projectId: 'miningassociation-8942c',
    authDomain: 'miningassociation-8942c.firebaseapp.com',
    databaseURL: 'https://miningassociation-8942c.firebaseio.com',
    storageBucket: 'miningassociation-8942c.appspot.com',
  );
}
